# Generated by Django 5.1.6 on 2025-03-11 13:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='custom_groups', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('objectif_de_poids_quotidien', models.FloatField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10, null=True)),
                ('fitbit_access_token', models.TextField(blank=True, null=True)),
                ('fitbit_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fitbit_refresh_token', models.TextField(blank=True, null=True)),
                ('fitbit_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, choices=[('student', 'Étudiant'), ('employee', 'Employé'), ('self_employed', 'Indépendant / Freelance'), ('business_owner', 'Entrepreneur'), ('healthcare_worker', 'Professionnel de santé'), ('teacher', 'Enseignant'), ('athlete', 'Sportif'), ('military', "Militaire / Forces de l'ordre"), ('unemployed', 'Sans emploi'), ('retired', 'Retraité')], max_length=50, null=True)),
                ('user_goal', models.CharField(blank=True, choices=[('lose_weight', 'Perte de poids'), ('gain_muscle', 'Prendre du muscle'), ('improve_endurance', 'Améliorer mon endurance'), ('strengthen_body', 'Renforcer mon corps'), ('increase_flexibility', 'Augmenter ma souplesse'), ('improve_posture', 'Améliorer ma posture')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('stress_score', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitbitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.IntegerField(default=0)),
                ('sedentary_minutes', models.IntegerField(default=0)),
                ('lightly_active_minutes', models.IntegerField(default=0)),
                ('fairly_active_minutes', models.IntegerField(default=0)),
                ('very_active_minutes', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0.0)),
                ('calories', models.IntegerField(default=0)),
                ('sleep_duration', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
