# Generated by Django 5.1.6 on 2025-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activite_physique',
            field=models.CharField(blank=True, choices=[('A', 'Moins de 30 minutes'), ('B', '30-60 minutes'), ('C', 'Plus de 60 minutes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='composition_corporelle',
            field=models.CharField(blank=True, choices=[('A', 'Haute graisse corporelle, faible dépense calorique'), ('B', 'Composition moyenne, dépense calorique modérée'), ('C', 'Mince/musclé avec une dépense calorique élevée')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='indicateurs_cardio',
            field=models.CharField(blank=True, choices=[('A', 'Fatigue rapide et essoufflement fréquent'), ('B', 'Supportable mais un peu essoufflé après un moment'), ('C', 'Facilement sans essoufflement')], max_length=50, null=True),
        ),
    ]
