# Generated by Django 5.1.6 on 2025-03-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_profile_activite_physique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='objectif_de_poids_quotidien',
            new_name='objectif_de_pas_quotidien',
        ),
    ]
