# Generated by Django 5.1.6 on 2025-03-11 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_rename_objectif_de_poids_quotidien_profile_objectif_de_pas_quotidien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_cluster_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pca_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FitbitDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.IntegerField(default=0)),
                ('sedentary_minutes', models.IntegerField(default=0)),
                ('lightly_active_minutes', models.IntegerField(default=0)),
                ('fairly_active_minutes', models.IntegerField(default=0)),
                ('very_active_minutes', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0.0)),
                ('calories', models.IntegerField(default=0)),
                ('sleep_duration', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
