# Generated by Django 5.1.6 on 2025-03-12 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_profile_assigned_cluster_profile_last_cluster_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWeeklyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('recommendation_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.workoutprogram')),
            ],
            options={
                'unique_together': {('user', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgramClusterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('avg_rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('workout_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.workoutprogram')),
            ],
            options={
                'unique_together': {('workout_program', 'cluster_id')},
            },
        ),
    ]
